# Preparación del Dataset: Statlog Australian Credit

## 1. Descripción del Dataset
Registro australiano de tarjetas de crédito, estructurado con tipos numéricos y categóricos estrictos (evaluación crediticia).

Aquí procesaremos y prepararemos los datos matemáticamente desde cero usando fórmulas puras, tal como se hace en el curso. Explicaremos paso a paso el código.

## 2. Importación de Librerías
Vamos a cargar las herramientas necesarias, usando lo más básico posible:

- `pandas` y `numpy`: para leer el archivo y manipular la tabla matemáticamente.
- `matplotlib.pyplot` y `seaborn`: para hacer gráficos simples en 2D (líneas, barras), nada en 3D para no complicarlo.

*Nota:* No usaremos funciones complejas o cajas negras para normalizar ni para dividir los datos, todo lo haremos "a mano" con simples matemáticas.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# NO usamos sklearn para transformar ni dividir datos.

## 3. Cargar y Explorar el Archivo (Dataset)
Aquí leemos el archivo base y mostramos cómo se ve. Revisamos la cantidad de filas y columnas que tenemos para entender su tamaño.

In [2]:
ruta = 'REPOSITORIOS_PARCIAL/7_Statlog (Australian Credit Approval) – UCI/statlog+australian+credit+approval/australian.dat'

tabla_datos = pd.read_csv(ruta, sep=' ', header=None)

# Mostramos tamaño (filas, columnas)
print('Tamaño del dataset:', tabla_datos.shape)

# Vemos las primeras 5 filas
tabla_datos.head()

# Imprimir información detallada del dataset
filas, columnas = tabla_datos.shape
print(f"\n--- INFORMACIÓN DEL DATASET ---")
print(f"Total de Filas (Ejemplos): {filas}")
print(f"Total de Columnas (Características): {columnas}\n")

Tamaño del dataset: (690, 15)

   0      1      2   3   4   5      6   7   8   9   10  11   12    13  14
0   1  22.08  11.46   2   4   4  1.585   0   0   0   1   2  100  1213   0
1   0  22.67   7.00   2   8   4  0.165   0   0   0   0   2  160     1   0
2   0  29.58   1.75   1   4   4  1.250   0   0   0   1   2  280     1   0
3   0  21.67  11.50   1   5   3  0.000   1   1  11   1   2    0     1   1
4   1  20.17   8.17   2   6   4  1.960   1   1  14   0   2   60   159   1

## 4. Análisis de Datos Vacíos o Faltantes
En la vida real, los datos no siempre vienen perfectos, hay casillas vacías (Nulos o NaN). 

En este caso, hemos decidido **eliminar la fila completa** si detectamos que tiene algún dato faltante. Esto asegura que la red neuronal solo aprenda de casos reales y 100% verídicos (no inventamos promedios ni asumimos valores vacíos), a costa de reducir la cantidad de ejemplos disponibles.

In [3]:
datos_nulos = tabla_datos.isnull().sum()
print('Columnas con casillas vacías antes de limpieza:')
print(datos_nulos[datos_nulos > 0])

# Eliminamos absolutamente cualquier fila que contenga un dato nulo (NaN)
filas_antes = len(tabla_datos)
tabla_datos = tabla_datos.dropna()
filas_despues = len(tabla_datos)

print(f"\nSe eliminaron {filas_antes - filas_despues} filas que contenían datos nulos.")
print('Nulos restantes sumados:', tabla_datos.isnull().sum().sum())

Columnas con casillas vacías:
Series([], dtype: int64)

Nulos restantes sumados: 0

## 5. Conversión de Textos a Números
Como la computadora o nuestra Red Neuronal no entiende palabras , necesitamos números. Usaremos una herramienta integrada muy sencilla llamada `get_dummies`.

Lo que hace es tomar las columnas de texto y crear columnas visuales llenas de ceros (`0`) y unos (`1`). Es directo y no necesitas complicarlo con diccionarios o For loops.

In [4]:
# Convertimos todo el texto a datos de 0 y 1 de forma directa y sencilla.
tabla_datos = pd.get_dummies(tabla_datos, dtype=int)

# Mostramos cómo quedó la tabla ahora, lista solo con formato numérico
tabla_datos.head()

   0      1      2   3   4   5      6   7   8   9   10  11   12    13  14
0   1  22.08  11.46   2   4   4  1.585   0   0   0   1   2  100  1213   0
1   0  22.67   7.00   2   8   4  0.165   0   0   0   0   2  160     1   0
2   0  29.58   1.75   1   4   4  1.250   0   0   0   1   2  280     1   0
3   0  21.67  11.50   1   5   3  0.000   1   1  11   1   2    0     1   1
4   1  20.17   8.17   2   6   4  1.960   1   1  14   0   2   60   159   1

## 6. Normalización de características (Feature Normalize)
Al visualizar los datos se puede observar que las características tienen diferentes magnitudes (por ejemplo, precios altísimos y números pequeños).

**La fórmula para calcular esto con escalado Z-Score es:**
$$ X_{norm} = \frac{X - \mu}{\sigma} $$

En código lo aplicamos usando las operaciones directas `mean()` (media) y `std()` (desviación estándar).

In [5]:
# 1. Calculamos la media (mu) y desviación estándar (sigma) para cada una de las columnas
mu = tabla_datos.mean()
sigma = tabla_datos.std()

# Para evitar errores por dividir entre cero (si la desviación es 0 en alguna columna), forzamos que sea mínimo 1
sigma_seguro = np.where(sigma == 0, 1, sigma)

# 2. Aplicamos la fórmula matemática exacta: (X - mu) / sigma
datos_normalizados = (tabla_datos - mu) / sigma_seguro

# Mostrar la tabla final convertida
datos_normalizados.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,0.688238,-0.800471,1.346134,0.542556,-0.915618,-0.347713,-0.190767,-1.046745,-0.863570,-0.493529,1.087120,0.237655,-0.488004,0.037353,-0.894654
1,-1.450880,-0.750696,0.450221,0.542556,0.170375,-0.347713,-0.615090,-1.046745,-0.863570,-0.493529,-0.918529,0.237655,-0.139490,-0.195272,-0.894654
2,-1.450880,-0.167735,-0.604384,-1.782685,-0.915618,-0.347713,-0.290872,-1.046745,-0.863570,-0.493529,1.087120,0.237655,0.557539,-0.195272,-0.894654
3,-1.450880,-0.835061,1.354169,-1.782685,-0.644120,-0.849641,-0.664395,0.953958,1.156306,1.768477,1.087120,0.237655,-1.068862,-0.195272,1.116131
4,0.688238,-0.961608,0.685248,0.542556,-0.372622,-0.347713,-0.078711,0.953958,1.156306,2.385388,-0.918529,0.237655,-0.720347,-0.164946,1.116131

## 7. Dividir el Dataset en 80/20 (Entrenamiento y Prueba)
Finalmente apartaremos el 80% de nuestros datos para que el modelo aprenda y un 20% para hacerle un examen y evaluarlo.
En lugar de una caja negra, apartamos las filas simplemente cortando las tablas basándonos en el porcentaje.

In [6]:
# Extraemos la última columna para usarla como objetivo de predicción (Variable Y o Target)
objetivo_col = datos_normalizados.columns[-1]
caracteristicas = datos_normalizados.drop(objetivo_col, axis=1)
objetivo = datos_normalizados[objetivo_col]

# --------- DIVISIÓN A MANO (80% Entrenamiento, 20% Prueba) ---------

# 1. Calculamos cuánto es el 80% entero de nuestras filas
total_filas = len(datos_normalizados)
ochenta_por_ciento = int(total_filas * 0.8)

# 2. Cortamos las tablas usando posiciones desde 0 hasta el 80%
X_entrenamiento = caracteristicas.iloc[:ochenta_por_ciento]
y_entrenamiento = objetivo.iloc[:ochenta_por_ciento]

# 3. Y para el resto (el 20% restante), usamos desde el 80% en adelante
X_prueba = caracteristicas.iloc[ochenta_por_ciento:]
y_prueba = objetivo.iloc[ochenta_por_ciento:]

print('Total datos Original:', total_filas, 'filas')
print('Datos para Entrenar (80%):', len(X_entrenamiento), 'filas')
print('Datos para Probar (20%):', len(X_prueba), 'filas')
print('\n¡El Dataset está preparado puramente usando lógica matemática!')

Total datos Original: 690 filas
Datos para Entrenar (80%): 552 filas
Datos para Probar (20%): 138 filas

¡El Dataset está preparado puramente usando lógica matemática!